name: nostr_widgets
description: "A Flutter UI package providing ready-to-use widgets."
version: 0.0.4
homepage: https://github.com/nogringo/nostr-widgets
repository: https://github.com/nogringo/nostr-widgets
topics:
  - ndk
  - nostr
  - widgets

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  amberflutter: ^0.0.9
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get: ^4.7.2
  http: ^1.4.0
  intl: ^0.20.2
  ndk: ^0.5.1
  ndk_amber: ^0.3.2
  nip01: ^0.3.0+1
  nip07_event_signer: ^1.0.2
  nip19: ^0.2.0
  pretty_qr_code: ^3.5.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
